# Generated by Django 3.1.1 on 2023-05-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.FloatField()),
                ('price_original', models.FloatField(null=True)),
                ('image', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('purity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('home_bar', models.BooleanField(default=False)),
                ('home_coin', models.BooleanField(default=False)),
                ('home_nugget', models.BooleanField(default=False)),
                ('home_ornament', models.BooleanField(default=False)),
                ('affordable', models.BooleanField(default=False)),
                ('top_rated', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('best_sellers', models.BooleanField(default=False)),
                ('deals', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
