# Generated by Django 3.1.1 on 2023-05-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230515_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalstaff',
            old_name='hospital_name',
            new_name='hospital',
        ),
    ]
