# Generated by Django 3.1.1 on 2023-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230515_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='availability',
        ),
        migrations.AddField(
            model_name='hospital',
            name='availabile_services',
            field=models.CharField(default=1, max_length=20000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='services_offered',
            field=models.CharField(max_length=50000),
        ),
    ]
