# Generated by Django 3.1.1 on 2023-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230515_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='availabile_services_and_resource',
        ),
        migrations.AddField(
            model_name='hospital',
            name='ambulance_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ambulance_contacts',
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='vacancies_available',
            field=models.BooleanField(default=False),
        ),
    ]
